const STORAGE_KEY='mandala-life-v2';
const categories=[
['🙏','신앙',['매일 성경 읽기','매일 묵주기도','주일미사','정기적인 고해성사','감사기도','성경 묵상 기록','성당 봉사','성지순례 준비']],
['👨‍👩‍👦','가족 & 아이들',['가족 기도','남편과 꾸준히 대화','아이들과 대화 시간','보민 대학 준비 지원','재하 성장 지원','가족 여행·추억 만들기','아이들 독립성 키우기','가족이 다시 함께 살 미래 준비']],
['💪','건강 & 몸',['수영 주 2–3회','10–20분 홈트','근력운동','복부·등 강화','단백질 챙기기','체중·허리 기록','수면 관리','정기검진 챙기기']],
['🇺🇸','영어',['정오 영어 공부','쉐도잉','Chunking 연습','하루 한 문장 말하기','생활영어 표현 익히기','주간 표현 복습','주말 영어 Writing','영어로 실제 대화하기']],
['✍️','글쓰기 & 배움',['짧게라도 글 쓰기','독서','인상 깊은 문장 기록','책 읽고 생각 남기기','내 경험 소재 모으기','ChatGPT와 생각 발전시키기','내 책 주제 찾아가기','책 한 권 쓰기']],
['✈️','여행 & 경험',['매년 한국 방문','가까운 나라 여행','미국 국내여행','유럽 여행','산티아고 순례','이스라엘·유럽 성지순례','스쿠버다이빙 배우기','스포츠댄스 배우기']],
['💰','재정 & 미래',['월 지출 파악','카드 결제 관리','저축 자동화','투자 현황 점검','여행자금 만들기','노후자금 점검','5년 재정목표 세우기','분기별 재정 리뷰']],
['🏠','심플한 생활',['토요일 집안일 루틴','하루 10분 정리','안 쓰는 물건 버리기','냉장고 음식 관리','물건 적게 사기','집안일 틈새 처리','필요한 만큼만 장보기','편안하고 단순한 집 유지']]
];
const defaults={center:'내가 원하는 삶을\n실제로 살아가기',names:{},logs:{},freq:{},focus:[]};
let data=JSON.parse(JSON.stringify(defaults)),selectedCat=0,selectedTask=0,month=new Date();month.setDate(1);
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x)data={...data,...x};normalizeFocus()}catch(e){}}
function normalizeFocus(){const byCat={};(data.focus||[]).forEach(id=>{const c=Number(String(id).split('-')[0]);if(c>=0&&c<8&&byCat[c]===undefined)byCat[c]=id});data.focus=Object.values(byCat)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function activeView(){return document.querySelector('.view.active')?.id||'homeView'}
function goBack(){const v=activeView();if(v==='taskView'){renderCategory();show('categoryView')}else if(v==='categoryView'||v==='focusView'){renderFull();show('homeView')}}
function taskId(c,t){return `${c}-${t}`}
function taskName(c,t){return data.names[taskId(c,t)]||categories[c][2][t]}
function renderFull(){const w=document.getElementById('fullGrid');w.innerHTML='';for(let i=0;i<9;i++){const b=document.createElement('button');b.className='homeCell'+(i===4?' homeCore':'');if(i===4){b.textContent=data.center}else{const c=i<4?i:i-1;b.innerHTML=`<span>${categories[c][0]}</span><b>${categories[c][1]}</b>`;b.onclick=()=>openCat(c)}w.appendChild(b)}}
function openCat(c){selectedCat=c;document.getElementById('categoryTitle').textContent=`${categories[c][0]} ${categories[c][1]}`;renderCategory();show('categoryView')}
function renderCategory(){const w=document.getElementById('categoryGrid');w.innerHTML='';for(let i=0;i<9;i++){const b=document.createElement('button');b.className='catCell'+(i===4?' catMain':'');if(i===4)b.textContent=`${categories[selectedCat][0]}\n${categories[selectedCat][1]}`;else{const t=i<4?i:i-1;b.textContent=taskName(selectedCat,t);b.onclick=()=>openTask(selectedCat,t)}w.appendChild(b)}}
function openTask(c,t){selectedCat=c;selectedTask=t;month=new Date();month.setDate(1);document.getElementById('taskCategory').textContent=`${categories[c][0]} ${categories[c][1]}`;document.getElementById('taskTitle').textContent=taskName(c,t);document.getElementById('frequency').value=data.freq[taskId(c,t)]||guessFreq(taskName(c,t));renderCalendar();show('taskView')}
function guessFreq(n){if(n.includes('주일미사')||n.includes('주간')||n.includes('토요일'))return'weekly1';if(n.includes('수영'))return'weekly3';if(n.includes('정기')||n.includes('분기')||n.includes('여행')||n.includes('순례')||n.includes('배우기')||n.includes('책 한 권'))return'project';return'daily'}
function dateKey(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay(),w=document.getElementById('calendar'),id=taskId(selectedCat,selectedTask),today=new Date();document.getElementById('monthLabel').textContent=`${y}년 ${m+1}월`;w.innerHTML='';for(let i=0;i<first;i++)w.appendChild(document.createElement('span'));for(let d=1;d<=days;d++){const k=dateKey(y,m,d),b=document.createElement('button');b.className='day';b.innerHTML=`<span>${d}</span>${data.logs[id]?.[k]?'<b>✓</b>':''}`;const dt=new Date(y,m,d);if(data.logs[id]?.[k])b.classList.add('checked');if(dt>today)b.disabled=true;b.onclick=()=>{data.logs[id]=data.logs[id]||{};data.logs[id][k]=!data.logs[id][k];save();renderCalendar()};w.appendChild(b)}renderRate(y,m,days,id)}
function renderRate(y,m,days,id){const now=new Date(),isCurrent=y===now.getFullYear()&&m===now.getMonth(),elapsed=isCurrent?now.getDate():days;let done=0;for(let d=1;d<=elapsed;d++)if(data.logs[id]?.[dateKey(y,m,d)])done++;const f=document.getElementById('frequency').value;let target=elapsed;if(f.startsWith('weekly'))target=Math.max(1,Math.ceil(elapsed/7)*Number(f.slice(-1)));if(f==='monthly1')target=1;if(f==='project')target=Math.max(done,1);const pct=Math.min(100,Math.round(done/target*100));document.getElementById('rateText').textContent=`${pct}%`;document.getElementById('rateFill').style.width=`${pct}%`;document.getElementById('rateDetail').textContent=`${done}회 기록 · 현재 기준 목표 ${target}회`}
function focusForCat(c){return (data.focus||[]).find(id=>Number(String(id).split('-')[0])===c)}
function renderFocus(){const w=document.getElementById('focusList');w.innerHTML='';categories.forEach((cat,c)=>{const id=focusForCat(c),b=document.createElement('button');b.className='focusItem';if(id){const t=Number(id.split('-')[1]);b.innerHTML=`<span>${cat[0]}</span><div><small>${cat[1]}</small><b>${taskName(c,t)}</b></div>`;b.onclick=()=>openTask(c,t)}else{b.innerHTML=`<span>${cat[0]}</span><div><small>${cat[1]}</small><b>아직 선택 안 함</b></div>`;b.onclick=()=>{document.getElementById('focusPicker').classList.remove('hidden');renderPicker(c)}}w.appendChild(b)})}
function renderPicker(onlyCat=null){const p=document.getElementById('focusPicker');p.innerHTML='<p>각 영역에서 하나씩 선택해. 새로 고르면 기존 선택이 바뀌어.</p>';categories.forEach((cat,c)=>{if(onlyCat!==null&&c!==onlyCat)return;const title=document.createElement('h3');title.textContent=`${cat[0]} ${cat[1]}`;p.appendChild(title);cat[2].forEach((_,t)=>{const id=taskId(c,t),b=document.createElement('button');b.className=focusForCat(c)===id?'picked':'';b.textContent=taskName(c,t);b.onclick=()=>{data.focus=(data.focus||[]).filter(x=>Number(String(x).split('-')[0])!==c);data.focus.push(id);save();renderFocus();renderPicker(onlyCat)};p.appendChild(b)})})}
load();renderFull();document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{if(b.dataset.back==='homeView')renderFull();show(b.dataset.back)});document.getElementById('focusBtn').onclick=()=>{renderFocus();show('focusView')};document.getElementById('chooseFocus').onclick=()=>{const p=document.getElementById('focusPicker');p.classList.toggle('hidden');if(!p.classList.contains('hidden'))renderPicker()};document.getElementById('frequency').onchange=e=>{data.freq[taskId(selectedCat,selectedTask)]=e.target.value;save();renderCalendar()};document.getElementById('prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};document.getElementById('editTaskBtn').onclick=()=>{const n=prompt('실천과제 이름을 수정해줘.',taskName(selectedCat,selectedTask));if(n&&n.trim()){data.names[taskId(selectedCat,selectedTask)]=n.trim();save();document.getElementById('taskTitle').textContent=n.trim();renderFull()}};
let touchX=0,touchY=0;document.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;touchX=e.touches[0].clientX;touchY=e.touches[0].clientY},{passive:true});document.addEventListener('touchend',e=>{if(!e.changedTouches.length||activeView()==='homeView')return;const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(dx>70&&Math.abs(dx)>Math.abs(dy)*1.35)goBack()},{passive:true});