const STORAGE_KEY='mandala-life-v2';
const categories=[
['🙏','신앙',['성경 읽기 & 묵상','54일 묵주기도','주일미사','누군가를 위한 화살기도','고해성사','성당 봉사','성지순례','신앙 공부하기']],
['👨‍👩‍👦','가족 & 아이들',['가족 성경 읽기','THANK YOU NOTE','질문으로 대화하기','아이에게 맡겨보기','아이들 학교·진로 지원','아이들 활동 지원','매년 한국 방문','Family Tradition 이어가기']],
['💪','건강 & 몸',['수영','홈 근력운동','단백질 챙기기','16시간 공복','피부 관리','장거리 여행 체력 만들기','약·영양제 챙기기','물 40oz 마시기']],
['📚','배움 & 취미',['English Life Daily & 쉐도잉','독서','글쓰기','취미','새로운 것 배우기','새로운 분야 탐색','여행 계획하기','투자 현황 점검 & 공부하기']],
['🧠','멘탈',['일희일비하지 않기','불안할때 몸 움직이기','걱정과 사실 구분하기','지금 할 수 있는 것 찾기','실패하기','일단 하기','결론 내리기','운전할때 화 안내기']],
['💛','인간성',['다정하게 대하기','그럴 수 있지','내가 먼저 하기','좋은 점 말해주기','잘 들어주기','선을 지키기','약속 지키기','반성하기']],
['🍀','운',['인사 잘하기','쓰레기 줍기','물건을 소중히 쓰기','좋은 에너지 가까이하기','응원받는 사람 되기','기회가 오면 잡아보기','작은 행운 알아보기','나도 운을 나눠주기']],
['🏠','심플한 생활',['미루지 않고 제자리로','집안 청소 한군데 하기','필요한 만큼만 사기','공간 비워두기','핸드폰 오래 봤다 싶으면 끊기','여행 자금 모으기','다음 여행 준비하기','식사 메뉴 미리 정하기']]
];
const defaults={center:'내가 원하는 삶을\n실제로 살아가기',names:{},logs:{},notes:{},freq:{},focus:[]};
let data=JSON.parse(JSON.stringify(defaults)),selectedCat=0,selectedTask=0,selectedDate='',month=new Date();month.setDate(1);
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x)data={...data,...x,notes:x.notes||{}};normalizeFocus()}catch(e){}}
function normalizeFocus(){const byCat={};(data.focus||[]).forEach(id=>{const c=Number(String(id).split('-')[0]);if(c>=0&&c<8&&byCat[c]===undefined)byCat[c]=id});data.focus=Object.values(byCat)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function activeView(){return document.querySelector('.view.active')?.id||'homeView'}
function goBack(){const v=activeView();if(v==='taskView'){renderCategory();show('categoryView')}else if(v==='categoryView'||v==='focusView'){renderFull();show('homeView')}}
function taskId(c,t){return `${c}-${t}`}
function taskName(c,t){const id=taskId(c,t);return Object.prototype.hasOwnProperty.call(data.names,id)?data.names[id]:categories[c][2][t]}
function todayKey(){const n=new Date();return dateKey(n.getFullYear(),n.getMonth(),n.getDate())}
function renderFull(){const w=document.getElementById('fullGrid');w.innerHTML='';for(let i=0;i<9;i++){const b=document.createElement('button');b.className='homeCell'+(i===4?' homeCore':'');if(i===4){b.textContent=data.center}else{const c=i<4?i:i-1;b.innerHTML=`<span>${categories[c][0]}</span><b>${categories[c][1]}</b>`;b.onclick=()=>openCat(c)}w.appendChild(b)}renderTodayActivity()}
function renderTodayActivity(){const k=todayKey(),items=[];let checks=0,memos=0;categories.forEach((cat,c)=>cat[2].forEach((_,t)=>{const id=taskId(c,t),checked=!!data.logs[id]?.[k],note=data.notes?.[id]?.[k]||'';if(checked)checks++;if(note)memos++;if(checked||note)items.push({c,t,checked,note})}));document.getElementById('todayCount').textContent=checks+memos;document.getElementById('todaySummary').innerHTML=`<span class="summaryChip">✓ 체크 ${checks}</span><span class="summaryChip">✎ 메모 ${memos}</span>`;const w=document.getElementById('todayRecent');w.innerHTML='';if(!items.length){w.innerHTML='<p class="emptyActivity">오늘 기록을 시작하면 여기에 하나씩 쌓여.</p>';return}items.slice(-3).reverse().forEach(x=>{const row=document.createElement('div');row.className='recentMini';row.innerHTML=`<span>${categories[x.c][0]}</span><div><b></b><p></p></div>`;row.querySelector('b').textContent=taskName(x.c,x.t);row.querySelector('p').textContent=x.note||(x.checked?'오늘 완료 ✓':'');row.onclick=()=>openTask(x.c,x.t);w.appendChild(row)})}
function openCat(c){selectedCat=c;document.getElementById('categoryTitle').textContent=`${categories[c][0]} ${categories[c][1]}`;renderCategory();show('categoryView')}
function renderCategory(){const w=document.getElementById('categoryGrid');w.innerHTML='';for(let i=0;i<9;i++){const b=document.createElement('button');b.className='catCell'+(i===4?' catMain':'');if(i===4)b.textContent=`${categories[selectedCat][0]}\n${categories[selectedCat][1]}`;else{const t=i<4?i:i-1,name=taskName(selectedCat,t);b.textContent=name||'＋ 빈칸';if(!name)b.classList.add('emptyTask');b.onclick=()=>openTask(selectedCat,t)}w.appendChild(b)}renderCategoryActivity()}
function renderCategoryActivity(){const now=new Date(),prefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-`,items=[];let checks=0,memos=0;categories[selectedCat][2].forEach((_,t)=>{const id=taskId(selectedCat,t);Object.entries(data.logs[id]||{}).forEach(([k,v])=>{if(v&&k.startsWith(prefix)){checks++;items.push({t,k,note:data.notes?.[id]?.[k]||'',checked:true})}});Object.entries(data.notes?.[id]||{}).forEach(([k,v])=>{if(v&&k.startsWith(prefix)){memos++;if(!data.logs[id]?.[k])items.push({t,k,note:v,checked:false})}})});document.getElementById('categoryMonthLabel').textContent=`${now.getMonth()+1}월`;document.getElementById('categoryCount').textContent=checks;document.getElementById('categorySummary').innerHTML=`<span class="summaryChip">✓ ${checks}번 기록</span><span class="summaryChip">✎ 메모 ${memos}</span>`;const w=document.getElementById('categoryRecent');w.innerHTML='';items.sort((a,b)=>b.k.localeCompare(a.k));if(!items.length){w.innerHTML='<p class="emptyActivity">이번 달 기록이 아직 없어.</p>';return}items.slice(0,3).forEach(x=>{const row=document.createElement('div');row.className='recentMini';row.innerHTML=`<span>${Number(x.k.slice(5,7))}/${Number(x.k.slice(8,10))}</span><div><b></b><p></p></div>`;row.querySelector('b').textContent=taskName(selectedCat,x.t);row.querySelector('p').textContent=x.note||(x.checked?'완료 ✓':'');row.onclick=()=>openTask(selectedCat,x.t);w.appendChild(row)})}
function openTask(c,t){selectedCat=c;selectedTask=t;month=new Date();month.setDate(1);const now=new Date();selectedDate=dateKey(now.getFullYear(),now.getMonth(),now.getDate());document.getElementById('taskCategory').textContent=`${categories[c][0]} ${categories[c][1]}`;document.getElementById('taskTitle').textContent=taskName(c,t)||'빈 실천과제';document.getElementById('frequency').value=data.freq[taskId(c,t)]||guessFreq(taskName(c,t));renderCalendar();renderNote();show('taskView')}
function guessFreq(n){if(n.includes('주일미사')||n.includes('주간')||n.includes('토요일')||n.includes('체중·허리')||n==='취미'||n.includes('새로운 것 배우기')||n.includes('새로운 분야 탐색'))return'weekly1';if(n.includes('홈 근력운동')||n.includes('피부 관리'))return'weekly3';if(n==='수영')return'weekly3';if(n.includes('고해성사'))return'monthly1';if(n.includes('성당 봉사')||n.includes('장거리 여행 체력')||n.includes('정기')||n.includes('분기')||n.includes('여행')||n.includes('순례')||n.includes('책 한 권')||n.includes('추억 기록')||n.includes('맡겨보기')||n.includes('지원'))return'project';return'daily'}
function dateKey(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function noteFor(id,k){return data.notes?.[id]?.[k]||''}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay(),w=document.getElementById('calendar'),id=taskId(selectedCat,selectedTask),today=new Date();document.getElementById('monthLabel').textContent=`${y}년 ${m+1}월`;w.innerHTML='';for(let i=0;i<first;i++)w.appendChild(document.createElement('span'));for(let d=1;d<=days;d++){const k=dateKey(y,m,d),b=document.createElement('button');b.className='day';b.innerHTML=`<span>${d}</span>${data.logs[id]?.[k]?'<b>✓</b>':''}`;const dt=new Date(y,m,d);if(data.logs[id]?.[k])b.classList.add('checked');if(noteFor(id,k))b.classList.add('hasNote');if(k===selectedDate)b.style.outline='2px solid #b9a5db';if(dt>today)b.disabled=true;b.onclick=()=>{selectedDate=k;data.logs[id]=data.logs[id]||{};data.logs[id][k]=!data.logs[id][k];save();renderCalendar();renderNote()};w.appendChild(b)}renderRate(y,m,days,id);renderNoteList(y,m,id)}
function renderRate(y,m,days,id){const now=new Date(),isCurrent=y===now.getFullYear()&&m===now.getMonth(),elapsed=isCurrent?now.getDate():days;let done=0;for(let d=1;d<=elapsed;d++)if(data.logs[id]?.[dateKey(y,m,d)])done++;const f=document.getElementById('frequency').value;let target=elapsed;if(f.startsWith('weekly'))target=Math.max(1,Math.ceil(elapsed/7)*Number(f.slice(-1)));if(f==='monthly1')target=1;if(f==='project')target=Math.max(done,1);const pct=Math.min(100,Math.round(done/target*100));document.getElementById('rateText').textContent=`${pct}%`;document.getElementById('rateFill').style.width=`${pct}%`;document.getElementById('rateDetail').textContent=`${done}회 기록 · 현재 기준 목표 ${target}회`}
function renderNote(){const id=taskId(selectedCat,selectedTask),parts=(selectedDate||'').split('-');document.getElementById('noteDate').textContent=parts.length===3?`${Number(parts[1])}/${Number(parts[2])}`:'';document.getElementById('dailyNote').value=noteFor(id,selectedDate)}
function renderNoteList(y,m,id){const w=document.getElementById('noteList');w.innerHTML='';const entries=Object.entries(data.notes?.[id]||{}).filter(([k,v])=>v&&k.startsWith(`${y}-${String(m+1).padStart(2,'0')}-`)).sort((a,b)=>b[0].localeCompare(a[0]));entries.forEach(([k,v])=>{const row=document.createElement('div');row.className='noteEntry';const d=Number(k.slice(-2));row.innerHTML=`<time>${m+1}/${d}</time><p></p><button aria-label="메모 삭제">×</button>`;row.querySelector('p').textContent=v;row.querySelector('p').onclick=()=>{selectedDate=k;renderNote();renderCalendar()};row.querySelector('button').onclick=()=>{delete data.notes[id][k];save();renderCalendar();renderNote()};w.appendChild(row)})}
function focusForCat(c){return (data.focus||[]).find(id=>Number(String(id).split('-')[0])===c)}
function renderFocus(){const w=document.getElementById('focusList');w.innerHTML='';categories.forEach((cat,c)=>{const id=focusForCat(c),b=document.createElement('button');b.className='focusItem';if(id){const t=Number(id.split('-')[1]);b.innerHTML=`<span>${cat[0]}</span><div><small>${cat[1]}</small><b>${taskName(c,t)||'빈칸'}</b></div>`;b.onclick=()=>openTask(c,t)}else{b.innerHTML=`<span>${cat[0]}</span><div><small>${cat[1]}</small><b>아직 선택 안 함</b></div>`;b.onclick=()=>{document.getElementById('focusPicker').classList.remove('hidden');renderPicker(c)}}w.appendChild(b)})}
function renderPicker(onlyCat=null){const p=document.getElementById('focusPicker');p.innerHTML='<p>각 영역에서 하나씩 선택해. 새로 고르면 기존 선택이 바뀌어.</p>';categories.forEach((cat,c)=>{if(onlyCat!==null&&c!==onlyCat)return;const title=document.createElement('h3');title.textContent=`${cat[0]} ${cat[1]}`;p.appendChild(title);cat[2].forEach((_,t)=>{const name=taskName(c,t);if(!name)return;const id=taskId(c,t),b=document.createElement('button');b.className=focusForCat(c)===id?'picked':'';b.textContent=name;b.onclick=()=>{data.focus=(data.focus||[]).filter(x=>Number(String(x).split('-')[0])!==c);data.focus.push(id);save();renderFocus();renderPicker(onlyCat)};p.appendChild(b)})})}
load();renderFull();document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{if(b.dataset.back==='homeView')renderFull();show(b.dataset.back)});document.getElementById('focusBtn').onclick=()=>{renderFocus();show('focusView')};document.getElementById('chooseFocus').onclick=()=>{const p=document.getElementById('focusPicker');p.classList.toggle('hidden');if(!p.classList.contains('hidden'))renderPicker()};document.getElementById('frequency').onchange=e=>{data.freq[taskId(selectedCat,selectedTask)]=e.target.value;save();renderCalendar()};document.getElementById('prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);selectedDate=dateKey(month.getFullYear(),month.getMonth(),1);renderCalendar();renderNote()};document.getElementById('nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);const now=new Date(),future=month.getFullYear()>now.getFullYear()||(month.getFullYear()===now.getFullYear()&&month.getMonth()>now.getMonth());selectedDate=future?'':dateKey(month.getFullYear(),month.getMonth(),month.getFullYear()===now.getFullYear()&&month.getMonth()===now.getMonth()?now.getDate():1);renderCalendar();renderNote()};document.getElementById('saveNoteBtn').onclick=()=>{if(!selectedDate)return;const id=taskId(selectedCat,selectedTask),text=document.getElementById('dailyNote').value.trim();data.notes[id]=data.notes[id]||{};if(text)data.notes[id][selectedDate]=text;else delete data.notes[id][selectedDate];save();renderCalendar();renderNote()};document.getElementById('editTaskBtn').onclick=()=>{const id=taskId(selectedCat,selectedTask),current=taskName(selectedCat,selectedTask);const n=prompt(current?'실천과제 이름을 수정해줘. 내용을 모두 지우고 확인하면 이 칸을 비울 수 있어.':'새 실천과제를 입력해줘.',current);if(n===null)return;data.names[id]=n.trim();if(!n.trim()){data.focus=(data.focus||[]).filter(x=>x!==id);delete data.freq[id]}save();document.getElementById('taskTitle').textContent=n.trim()||'빈 실천과제';renderCategory()};
let touchX=0,touchY=0;document.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;touchX=e.touches[0].clientX;touchY=e.touches[0].clientY},{passive:true});document.addEventListener('touchend',e=>{if(!e.changedTouches.length||activeView()==='homeView')return;const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(dx>70&&Math.abs(dx)>Math.abs(dy)*1.35)goBack()},{passive:true});